# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d8e208135a7107c7c601424c2a3e4ff9e4462f9da628cb17a5b79841be19222994b539c6b0f8b470e961e6bdd0a8f79d50c1dcc8109db83237b6b2f3a3e8fb

test:
  secret_key_base: d8b999d84b2abea44d6bd9811f941c12f73a9cc421a403d47af465bb3c7a616f5e78af7adfd80ab68853e6267382c8349291f6ed198fe88b5b9122e33bf7aa7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
